# config.yaml

# Configurações Globais do Benchmark
settings:
  output_base_dir: "output_runs/manual_execution" # Diretório base relativo ao diretório de build
  epsilon_tolerance: 1.0e-4
  max_iterations: 5
  l_curve_iterations: 5 # Numero de iteracoes para calcular a curva L e encontrar o ponto otimo
  save_intermediate_images: true # true para salvar imagem a cada iteração, false para salvar só a final
  num_omp_threads: 4 # 0 para usar o máximo padrão do OpenMP, ou especifique um número

# Definição dos Conjuntos de Teste Disponíveis
datasets:
  - name: "60x60_G1"
    description: "60x60 (Sinal G-1)"
    h_matrix_csv: "data/H-1.csv"
    g_signal_csv: "data/G-1.csv"
    image_rows: 60
    image_cols: 60

  - name: "60x60_G2"
    description: "60x60 (Sinal G-2)"
    h_matrix_csv: "data/H-1.csv"
    g_signal_csv: "data/G-2.csv"
    image_rows: 60
    image_cols: 60

  - name: "60x60_A1"
    description: "60x60 (Sinal A-1)"
    h_matrix_csv: "data/H-1.csv"
    g_signal_csv: "data/A-60x60-1.csv"
    image_rows: 60
    image_cols: 60

  - name: "30x30_g1"
    description: "30x30 (Sinal g-1)"
    h_matrix_csv: "data/H-2.csv"
    g_signal_csv: "data/g-30x30-1.csv"
    image_rows: 30
    image_cols: 30

  - name: "30x30_g2"
    description: "30x30 (Sinal g-2)"
    h_matrix_csv: "data/H-2.csv"
    g_signal_csv: "data/g-30x30-2.csv"
    image_rows: 30
    image_cols: 30

  - name: "30x30_A1"
    description: "30x30 (Sinal A-1)"
    h_matrix_csv: "data/H-2.csv"
    g_signal_csv: "data/A-30x30-1.csv"
    image_rows: 30
    image_cols: 30

# Definição dos Métodos de Reconstrução a serem testados
methods:
  - name: "sparse_standard"
    description: "CGNR esparso padrao"
    solver: "cgnr_standard"
    use_binary: true
    is_baseline: false

  - name: "sparse_jacobi"
    description: "CGNR esparso com pre-condicionador Jacobi"
    solver: "cgnr_jacobi"
    use_binary: true
    is_baseline: false

# Quais comparações/pipelines executar
run_pipelines:
  - name: "Sparse_Comparison"
    description: "Compara os metodos esparsos CGNR e Jacobi"
    methods:
      - "sparse_standard"
      - "sparse_jacobi"
    datasets:
      - "30x30_g1"
      - "30x30_g2"
      - "30x30_A1"
      - "60x60_G1"
      - "60x60_G2"
      - "60x60_A1"
